name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build win-x64
      run: dotnet publish src/Elmah.Io.Cli/Elmah.Io.Cli.csproj -c Release --runtime win-x64 --self-contained -o elmahio-win-x64 /p:AssemblyVersion=1.0.${{ github.run_number }}

    - name: Build linux-x64
      run: dotnet publish src/Elmah.Io.Cli/Elmah.Io.Cli.csproj -c Release --runtime linux-x64 --self-contained -o elmahio-linux-x64 /p:AssemblyVersion=1.0.${{ github.run_number }}

    - name: Build osx-x64
      run: dotnet publish src/Elmah.Io.Cli/Elmah.Io.Cli.csproj -c Release --runtime osx-x64 --self-contained -o elmahio-osx-x64 /p:AssemblyVersion=1.0.${{ github.run_number }}

    - name: Build osx-arm64
      run: dotnet publish src/Elmah.Io.Cli/Elmah.Io.Cli.csproj -c Release --runtime osx-arm64 --self-contained -o elmahio-osx-arm64 /p:AssemblyVersion=1.0.${{ github.run_number }}

    - name: Pack .NET tool
      run: dotnet pack -c Release src/Elmah.Io.Cli/Elmah.Io.Cli.csproj /p:Version=1.0.${{ github.run_number }}

    - name: Pack executables
      shell: bash
      run: |
        mkdir -p artifacts
        7z a -tzip "./artifacts/elmahio-win-x64.zip" "./elmahio-win-x64/*"
        tar czvf "./artifacts/elmahio-linux-x64.tar.gz" "elmahio-linux-x64"
        tar czvf "./artifacts/elmahio-osx-x64.tar.gz" "elmahio-osx-x64"
        tar czvf "./artifacts/elmahio-osx-arm64.tar.gz" "elmahio-osx-arm64"
        rm -r "elmahio-win-x64" "elmahio-linux-x64" "elmahio-osx-x64" "elmahio-osx-arm64"

    - name: Create Release
      if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./artifacts/elmahio-win-x64.zip
          ./artifacts/elmahio-linux-x64.tar.gz
          ./artifacts/elmahio-osx-x64.tar.gz
          ./artifacts/elmahio-osx-arm64.tar.gz
        tag_name: 1.0.${{ github.run_number }}
        name: 1.0.${{ github.run_number }}
        draft: false
        fail_on_unmatched_files: true
        generate_release_notes: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to GitHub Packages
      if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      run: |
        dotnet nuget add source \
          --username jasonnissen \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text \
          --name github \
          "https://nuget.pkg.github.com/FarReach/index.json"
        dotnet nuget push \
          src/Elmah.Io.Cli/nupkg/FarReach.Elmah.Io.Cli.1.0.${{ github.run_number }}.nupkg \
          --source github
